### ISSUE TITLE
Duidelijk maken wanneer 3e partijen dingen in het lab kunnen organiseren

### ISSUE THREAD

**Issue by raboof** [bibliotheekdeventer/lab#1]
Volgens mij is dit voldoende beantwoord op https://www.bibliotheekdeventer.nl/in-de-bibliotheek/ruimte-huren en kunnen we mensen daarnaar doorverwijzen. Daar staat dat je voor openbare initiatieven op de pleinen kunt mailen naar marktmeesters@bibliotheekdeventer.nl .

**Comment by raboof** [comment]
@ReinhartVoulon ik denk dat we deze taak kunnen sluiten, of zijn er nog dingen die duidelijker gemaakt moeten worden?

**Comment by ReinhartVoulon** [comment]
Ja, denk ik ook, lijkt me ook zeker voldoende voor nu. Tarieven over besloten activiteiten met de machines of verjaardagsfeestjes zijn nog niet helemaal duidelijk, maar die vragen komen dan vanzelf bij marktmeesters terecht, en worden ook duidelijker nu de beschrijvingen bij de machines en het gebruik ervan concreter wordt.

**Comment by raboof** [comment]
Ik zie dat je #10 aangemaakt hebt voor de beschrijvingen van de machines :+1:
