### ISSUE TITLE
Tarieven machines uitwerken

### ISSUE THREAD

**Issue by ReinhartVoulon** [bibliotheekdeventer/lab#11]
We hebben nog niet voor alle machines een uitgebreid kostenplaatje gemaakt (onderhoud/materiaal/enz), heeft hoge prioriteit.

* [x] Plotter
* [x] Lasersnijder
* [ ] 3D-printers

Extra onderzoek naar kosten van verschillende materialen, kwaliteit van leveranciers e.d. nog wel wenselijk.

**Comment by raboof** [comment]
@ReinhartVoulon waar vind ik de tarieven?

**Comment by raboof** [comment]
vanmiddag gedaan
