### ISSUE TITLE
Naam van het Bieblab

### ISSUE THREAD

**Issue by ReinhartVoulon** [bibliotheekdeventer/lab#12]
Hallo Allen (That is: Hallo Arnout, voorlopig althans.)

We zoeken nog een goede naam. De ruimte waar wij werken in de bieb heet het Innovatieplein, maar het beestje zelf zou ook een naam moeten hebben, een plein alleen is niets zonder goede caféetjes, alleen maar een waaigat.
Fablab mogen we officieel niet heten. Ik ga voor het Bieblab. Andere suggesties?

**Comment by raboof** [comment]
Helemaal mee eens dat het de moeite waard is een naam te hebben voor 'ons' als 'lab': het innovatieplein staat immers ook open voor andere activiteiten, en ik kan me voorstellen dat we soms iets willen doen dat wel 'bij het lab hoort' maar misschien een keer op een andere locatie (concreet bijvoorbeeld de TechTeach-sessies op de begane grond toen we daar nog terecht konden).

Ik vind 'Bieblab' al leuk maar nog wel wat algemeen: er zullen steeds meer bibliotheken komen met een lab. Korte brainstorm:
* Iets met 'space'? Klinkt mooi futuristisch en heeft links naar andere concepten als 'makerspace' en 'hackerspace' zonder daar direct onder te hoeven vallen. Heeft wel hetzelfde probleem als 'plein' dat het klinkt alsof het meer om de locatie dan om de ontmoeting gaat.
* Iets met een link naar Deventer?
* Iets met 'innovatie' (hoewel dat zelf een nogal overgebruikt woord is)
* Iets met 'experimenteren'
* Iets met 'maken'
* Iets met 'tech' (want we doen denk ik zowel 'techniek' als 'technologie')

**Comment by raboof** [comment]
Ik zie al andere groepen die de naam 'BiebLab' gebruiken, bijv https://www.bibliotheekwestland.nl/actueel/bieblab.html en https://www.oostachterhoek.nl/BIEBlab.html en https://www.debibliotheekaanzet.nl/activiteiten/bieblab .

Hebben we niet nog een leuke uitvinder of techneut in de Deventer geschiedenis? Ik zie zogauw niets in https://nl.wikipedia.org/wiki/Lijst_van_Deventenaren

**Comment by raboof** [comment]
Bibliotheek Noordwest Veluwe heeft een 'AppCamp' en 'Digital Hangout'. https://www.bibliotheeknoordwestveluwe.nl/leren/digitale-geletterdheid/digital-hangout.html

Ik zou het mooi vinden het wat breder te houden, tech is ook analoog :)

**Comment by raboof** [comment]
Iets in de hoek werkplaats/atelier/workshop/garage/.. misschien?

**Comment by raboof** [comment]
We kiezen voor 'makersplaats'. Nog een beetje 'generic', maargoed
