### ISSUE TITLE
Soms valt verbinding met plotter uit

### ISSUE THREAD

**Issue by ReinhartVoulon** [bibliotheekdeventer/lab#27]
Soms valt verbinding met plotter uit, dat kan ook midden tijdens het snijden van een tekening zijn.
opnieuw printen lukt niet, verbinding blijft verbroken.
usbkabel uit en in pluggen herstelt de verbinding weer.

Meer details heb ik nog niet, vul ik aan wanneer ik ze tegenkom.

zie screenshot voor de melding
![473f5c84c5f795e1c602a0a0379c81c89d8d9cca3253e1c20e313e9d8f2fb2ef](https://user-images.githubusercontent.com/46559029/121210421-f3b21900-c87b-11eb-8a34-c96f9ad60ce7.jpg)

**Comment by raboof** [comment]
Bedankt! Die foutmelding komt inderdaad overeen bij een onderbroken verbinding.

Het zou natuurlijk een hardwareprobleem kunnen zijn, maar laten we daar niet direct vanuit gaan. Wanneer het nog een keer voorkomt zou ik het interessant vinden om te weten wat de output is wanneer je in een terminal `dmesg` uitvoert. Dat is waarschijnlijk een heleboel tekst, maar hopelijk is het laatste stuk genoeg :).

Ik ben ook benieuwd naar de logging van inkcut, maar daar is misschien niet zo makkelijk achter te komen, dus laten we met dmesg beginnen.

**Comment by raboof** [comment]
> Wanneer het nog een keer voorkomt zou ik het interessant vinden om te weten wat de output is wanneer je in een terminal `dmesg` uitvoert. Dat is waarschijnlijk een heleboel tekst, maar hopelijk is het laatste stuk genoeg :).

Volgende actie voor Arnout: image aanpassen zodat bij het opstarten `dmesg` en Inkscape vanuit een terminal geopend worden, zodat deze informatie makkelijker verzameld kan worden.

**Comment by raboof** [comment]
Lijkt toch opgelost te zijn nadat Koen de machine een grondige onderhouds/schoonmaakbeurt gegeven heeft

**Comment by raboof** [comment]
(mocht dit toch weer voorkomen dan is https://github.com/inkcut/inkcut/issues/306 ook iets om naar te kijken)
